### ISSUE TITLE
speed_order variable is not contained in the controller object

### ISSUE THREAD

**Issue by Yanok35** [cogip/mcu-firmware#8]
https://github.com/cogip/mcu-firmware/blob/806ee581f7701aeb0105c97a5bd75f3a6150af5e/controllers/include/ctrl.h#L97-L100

The "speed_order" member variable has been designed to be private one. It's content should not be modified outside the object, asynchronously, without passing by relevant accessor.

**Comment by Kheprys** [comment]
This has been corrected by the highlighted commits.
Let's close it.
