### ISSUE TITLE
Implement system monitoring module

### ISSUE THREAD

**Issue by gdoffe** [cogip/mcu-firmware#85]
This module should monitor following informations
- [x] Heap size
- [x] Heap allocation guardian
- [x] Thread stack size

**Comment by gdoffe** [comment]
This module should monitor following informations
* Heap size
* Thread stack size
* Thread overtaking time
* Thread runtime
* Thread switch occurences

**Comment by ecourtois** [comment]
It would also be interesting to record dynamic allocations to avoid them:
```CPP
static size_t allocated = 0;

void* operator new(size_t sz) {
    allocated += sz;
    std::cout << "[allocating " << sz << " bytes] total = " << allocated << "\n";
    return std::malloc(sz);
}
```
